apiVersion: v1
kind: Service
metadata:
  name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
  labels:
{{ include "octobox-chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "octobox-chart.name" . }}-{{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
