apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "octobox-chart.fullname" . }}-{{ .Values.cronjob.name }}
  labels:
{{ include "octobox-chart.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "octobox-chart.name" . }}-{{ .Values.cronjob.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "octobox-chart.name" . }}-{{ .Values.cronjob.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      template:
        spec:
        {{- with .Values.app.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
        {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: {{ .Chart.Name }}-{{ .Values.cronjob.name }}
              image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
              imagePullPolicy: {{ .Values.app.image.pullPolicy }}
              command: {{ .Values.cronjob.command }}
              args: {{ .Values.cronjob.args }}
              env:
                - name: GITHUB_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: GITHUB_CLIENT_SECRET
                - name: OCTOBOX_DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OCTOBOX_DATABASE_USERNAME
                - name: OCTOBOX_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OCTOBOX_DATABASE_PASSWORD
                - name: REDIS_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: REDIS_URL
                - name: SECRET_KEY_BASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: SECRET_KEY_BASE
                - name: DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: DATABASE
                - name: FETCH_SUBJECT
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: FETCH_SUBJECT
                - name: GITHUB_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: GITHUB_CLIENT_ID
                - name: GITHUB_SCOPE
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: GITHUB_SCOPE
                - name: GA_ANALYTICS_ID
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: GA_ANALYTICS_ID
                - name: MINIMUM_REFRESH_INTERVAL
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: MINIMUM_REFRESH_INTERVAL
                - name: OCTOBOX_DATABASE_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OCTOBOX_DATABASE_HOST
                - name: OCTOBOX_DATABASE_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OCTOBOX_DATABASE_NAME
                - name: OCTOBOX_DATABASE_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OCTOBOX_DATABASE_PORT
                - name: OPEN_IN_SAME_TAB
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: OPEN_IN_SAME_TAB
                - name: PERSONAL_ACCESS_TOKENS_ENABLED
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: PERSONAL_ACCESS_TOKENS_ENABLED
                - name: PUSH_NOTIFICATIONS
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: PUSH_NOTIFICATIONS
                - name: RAILS_ENV
                  valueFrom:
                    configMapKeyRef:
                      name: {{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}
                      key: RAILS_ENV
