apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
data:
  database: "{{ .Values.config.database }}"
  fetchSubject: "{{ .Values.config.fetchSubject }}"
  githubClientId: "{{ .Values.config.githubClientId }}"
  githubScope: "{{ .Values.config.githubScope }}"
  gaAnalyticsId: "{{ .Values.config.gaAnalyticsId }}"
  minimumRefreshInterval: "{{ .Values.config.minimumRefreshInterval }}"
  octoboxDatabaseHost: "{{ .Values.config.octoboxDatabaseHost }}"
  octoboxDatabaseName: "{{ .Values.config.octoboxDatabaseName }}"
  octoboxDatabasePort: "{{ .Values.config.octoboxDatabasePort }}"
  openInSameTab: "{{ .Values.config.openInSameTab }}"
  personalAccessTokensEnabled: "{{ .Values.config.personalAccessTokensEnabled }}"
  pushNotifications: "{{ .Values.config.pushNotifications }}"
  railsEnv: "{{ .Values.config.railsEnv }}"
  websocketAllowedOrigins: "{{ .Values.config.websocketAllowedOrigins }}"
