apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "octobox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "octobox.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "octobox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: githubClientSecret
            - name: OCTOBOX_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: octoboxDatabasePassword
            - name: OCTOBOX_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: octoboxDatabaseUsername
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: redisUrl
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: secretKeyBase
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: database
            - name: FETCH_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: fetchSubject
            - name: GA_ANALYTICS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: gaAnalyticsId
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: githubClientId
            - name: GITHUB_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: githubScope
            - name: MINIMUM_REFRESH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: minimumRefreshInterval
            - name: OCTOBOX_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: octoboxDatabaseHost
            - name: OCTOBOX_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: octoboxDatabaseName
            - name: OCTOBOX_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: octoboxDatabasePort
            - name: OPEN_IN_SAME_TAB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: openInSameTab
            - name: PERSONAL_ACCESS_TOKENS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: personalAccessTokensEnabled
            - name: PUSH_NOTIFICATIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: pushNotifications
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: railsEnv
            - name: WEBSOCKET_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "octobox.fullname" . }}
                  key: websocketAllowedOrigins
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
