---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octobox-chart.fullname" . }}-{{ .Values.nginx.name }}
  labels:
{{ include "octobox-chart.labels" . | indent 4 }}
data:
  default.conf: |
    server {
      listen 443 ssl http2;
      listen [::]:443 ssl http2;

      ssl on;

      ssl_certificate /etc/nginx/ssl/cert.pem;
      ssl_certificate_key /etc/nginx/ssl/key.pem;

      server_name _;

      set_real_ip_from 0.0.0.0/0;
      real_ip_header X-Forwarded-For;

      location ~ ^/(assets/|android-icon-|apple-icon|browserconfig.xml|favicon|icon/|manifest.json|ms-icon-|robots.txt) {
        root /usr/src/app/public/;

        try_files $uri =404;

        expires 1y;
        add_header Cache-Control "public,max-age=31536000,immutable";

        access_log off;
        gzip on;
        gzip_types *;
      }

      location / {
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://{{ include "octobox-chart.fullname" . }}-{{ .Values.app.name }}:3000;
      }
    }
